### ISSUE TITLE
Not able to populate multiple-select  options by clicking edit button

### ISSUE THREAD

**Issue by iamxinyijiang** [iamxinyijiang/Group-Project-One#15]
1, When clicking edit button,  page not able to populate "assigned to" value if more than one options were chosen creating the task.
    ps. single option works fine, I think.

2, not able to overwrite entry with same task id currently

**Comment by jiazhen-weng** [comment]
set option's selected attribute to true by iterate check assignedTo element of the task object

**Comment by iamxinyijiang** [comment]
resolved! Kudos to Jimmy!
